### ISSUE TITLE
Very low contrast when editing a code block on dark mode

### ISSUE THREAD

**Issue by draganczukp** [redimp/otterwiki#103]
The default font color has a really bad contrast of just 2:1 - https://webaim.org/resources/contrastchecker/?fcolor=4C566A&bcolor=25282C

![image](https://github.com/redimp/otterwiki/assets/6382044/c131ee0a-20a5-4877-be78-1e7a2ef4a313)

The recommendation for small text (which I'd argue this falls under) is 7:1. Changing the code text color to `#B5BCC9`, done by changing the `L` component of the HSV color to 75% boosts the contrast to 7.75:1, and makes the text a lot easier to read

**Comment by redimp** [comment]
Hey @draganczukp,

Thank you for bringing this to my attention. Part of the problem here is that the fenced code block with a language is rendered as `comment`:

![image](https://github.com/redimp/otterwiki/assets/112056/db906561-afd9-488a-8f0a-104302c520fc)

With `#B5BCC9` as `.dark-mode .cm-s-otterwiki span.cm-comment` is the comment barely distinguishable:

![image](https://github.com/redimp/otterwiki/assets/112056/7ca4db76-fa27-4d1a-86a3-a4b6b6ef20ac)

I don't see a harm in colorizing the comments, what do you think about `#6BBAFF`? e.g.

![image](https://github.com/redimp/otterwiki/assets/112056/81d60aa3-8e27-430f-98f0-cad775f29806)

This has a contrast ratio of 7.11:1.
