### ISSUE TITLE
Settings stored in the database override those set in the settings.cfg?

### ISSUE THREAD

**Issue by mattock** [redimp/otterwiki#135]
Changes to settings.cfg seem not to have any effect after the settings have been save to the database. I've tested this with SITE_NAME, SITE_LOGO and SITE_ICON, but a quick look at server.py does not reveal any special treatment for those keys. Is my assessment correct?

My expectation would have been that settings in the configuration file (settings.cfg) are always respected as the "source of truth". That enables changing the configuration without poking at database contents or doing changes manually via Otterwiki web admin page. At minimum I think the documentation ([here](https://otterwiki.com/Configuration)) should be changed to reflect how Otterwiki loads the configuration.

**Comment by redimp** [comment]
Hey @mattock, what you've observed and read in the code is correct and works as intended ... but I agree, this can be counterintuitive and should be documented. Thank you for bringing this up!

How An Otter Wiki can be configured grew over time. At first there was only the `settings.cfg` and with the docker image came the environment variables and later the admin interface, that stores the settings in the database.

The implementation of the behaviour you expected is tricky: The `settings.cfg` is loaded first, the environment variables second .. because the `SQLALCHEMY_DATABASE_URI` has to be configured to load the database. After loading the settings from the database, the setings from the `settings.cfg` and the environment variables could be re-applied, but this feels hacky. And that these variables are immutable must be visible in the admin interface.

I will give it some thought. I can imagine circumstances where this makes sense.

**Comment by redimp** [comment]
Updated the documentation https://otterwiki.com/-/commit/5819b3
