### ISSUE TITLE
Warn the user when navigating away from unsaved changes 

### ISSUE THREAD

**Issue by redimp** [redimp/otterwiki#64]
The wiki should display a warning, in case the user has edited the page, is either in the Editor or on the Preview Page and would discard the changes when naviating away from there.

Reported in #60.

**Comment by bverkron** [comment]
Was just thinking... rather than just a warning alone I wonder if it would be possible to bring up the save / commit dialog with the warning inside that dialog so that the user can either cancel and remain on the page or save / commit and continue navigating away from the page. Might be a smooth way to do it so that they don't have to dismiss the warning, manually trigger the save operation, and then trigger the navigation again.

**Comment by redimp** [comment]
Released in [2.5.0](https://github.com/redimp/otterwiki/releases/tag/v2.5.0).
